# Generated by Django 2.2.12 on 2022-10-20 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames must be unqiue, ')])),
                ('description', models.TextField(max_length=120)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0, message='Value must be bigger than 0!'), django.core.validators.MaxLengthValidator(100, message='Value must be less than 100!')])),
            ],
        ),
    ]
