# Generated by Django 2.2.12 on 2022-10-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='username',
            new_name='name',
        ),
    ]
